### ISSUE TITLE
Publish Github IO Page

### ISSUE THREAD

**Issue by kshitijrajsharma** [osgeonepal/rollingdoc#1]
## Need : 
- A Github page that can act as website to publish information until we have one official 
- Only README converted to docs will be sufficient  

## Suggested Solution : 

- [mkdocs](https://www.mkdocs.org/) Could fit the purpose  

## How to contribute ? 

- Start working on setting up the github action , Add related docs or Readme !

**Comment by HEM2058** [comment]
I am interested?

**Comment by kshitijrajsharma** [comment]
Sure Go ahead !

**Comment by kshitijrajsharma** [comment]
- Resolved by #15
