### ISSUE TITLE
More info;

### ISSUE THREAD

**Issue by Lalitgis** [osgeonepal/rollingdoc#23]
More info;

- [ ] Is the training related to open source geospatial community?
- [ ] Invitation to participate and speakers

Divide checklists into two catagories `pre-event` & `post-event`. You might also need to merge the previous checklist with below,

Post Event:

- [ ] Post on social media
- [ ] summary of the event
- [ ] Thank you note for the speakers & participants 
- [ ] feedback from the participants and speakers
- [ ] Give a digital token of love to the speaker (if possible)

Pre-event:

- [ ] Communication/discussion started in discord channel (training & collaboration)
- [ ] Decide the target group, make sure the selection of the speaker is relevant to the event
- [ ] Checklist pass for speaker
    - [ ] Speaker is active in open source geospatial community 
    - [ ] Had relevant experience
    - [ ] Not associated with business marketing 
    - [ ] tbd....
- [ ] Ask for the volunteers 
    - [ ] Event facilitator 
    - [ ] Social media coordinator
    - [ ] Email & meeting link manager
    - [ ] Note-taking 

- [ ] Ask for a poster (poster and communication channel)
- [ ] Event outline (what are the topics that will be covered, what to expect, timeline)

This is only a rough sketch list from Kshitij and tek's top of mind & Subject to change . Take this as only reference

_Originally posted by @iamtekson in https://github.com/osgeonepal/rollingdoc/issues/18#issuecomment-1903220569_

**Comment by Pratichhya** [comment]
> * [ ]  Invitation to participate and speakers

I think the invitation to participants and speakers should be in two separate checklist

> Post Event:
> 
> * [ ]  Post on social media
> * [ ]  summary of the event
> * [ ]  Thank you note for the speakers & participants
> * [ ]  feedback from the participants and speakers
> * [ ]  Give a digital token of love to the speaker (if possible)

How about creating the Post-event checklist below the pre-event checklist?


> Pre-event:
> 
> * [ ]  Communication/discussion started in discord channel (training & collaboration)
> * [ ]  Decide the target group, make sure the selection of the speaker is relevant to the event
> * [ ]  Checklist pass for speaker
>   
>   * [ ]  Speaker is active in open source geospatial community
>   * [ ]  Had a relevant experience
>   * [ ]  Not associated with business marketing

Are we sure not to let speakers be associated with business marketing, or should it be that the presentation is not associated with business marketing?

>   * [ ]  tbd....

I think we should finalise the tbd... soon.

> * [ ]  Ask for the volunteers
>   

How about we divide it into tasks and subtasks? volunteer needed. If not, ignore, else request for a volunteer. 

>   * [ ]  Event facilitator
>   * [ ]  Social media coordinator
>   * [ ]  Email & meeting link manager

This will further be two task I guess: 
1. mail to speaker
2. mail to participants

>   * [ ]  Note-taking

What is note-taking?

> * [ ]  Ask for a poster (poster and communication channel)

What do you say about keeping poster preparation ahead of social media coordination?

> * [ ]  Event outline (what are the topics that will be covered, what to expect, timeline)

I guess this should be after getting a response from the speaker and before preparing banner


> This is only a rough sketch list from Kshitij and tek's top of mind & Subject to change. Take this as only reference
> 
> _Originally posted by @iamtekson in [#18 (comment)](https://github.com/osgeonepal/rollingdoc/issues/18#issuecomment-1903220569)_

**Comment by Pratichhya** [comment]
@Lalitgis, I understand that it's a draft version, and it is really nice work. Thank you. But how about slowly fine-tuning it so that it can fully be presented?

@iamtekson, if I understood correctly, this issue will remain open to guide the event organiser to follow the check-list on their own version. Please correct me if I am wrong.

Also, please let me know if I am being pushy person, sorry in advance just incase 😄

**Comment by iamtekson** [comment]
Hi dd, initially, our plan was to add the issue template on repo and add those checklists for the training and knowledge sharing. After that, the issue should be linked with PR and contribute to the actual website.

**Comment by iamtekson** [comment]
Now, based on the two issues #18 #23, I am now preparing the issue template and will share here. Please add your thoughts in issue template and we can finalize that one too.

> I think the invitation to participants and speakers should be in two separate checklist
> How about creating the Post-event checklist below the pre-event checklist?
> How about we divide it into tasks and subtasks? volunteer needed. If not, ignore, else request for a volunteer.
>What do you say about keeping poster preparation ahead of social media coordination?
>I guess this should be after getting a response from the speaker and before preparing banner

Done!

> Are we sure not to let speakers be associated with business marketing, or should it be that the presentation is not associated with business marketing?

This mean, the speaker can be associated with business but he shouldn't promote his/her business marketing during the event.

> I think we should finalise the tbd... soon.

I just replaced by "add more if any..."

>This will further be two task I guess:

These things are under invitation to (participates & speakers). I will merge it with invitation one.

>What is note-taking?

It means, the volunteer should take the important notes during the meeting such as links, important documents etc.

**Comment by iamtekson** [comment]
Now, I just added the [issue template](https://github.com/osgeonepal/rollingdoc/blob/master/.github/ISSUE_TEMPLATE/training---knowledge-sharing-checklist.md), I tried to include all the details mentioned in #23 and #18. Please close this issue @Lalitgis if you think the issue template is good enough.

You can test creating the new issue here with this template: https://github.com/osgeonepal/rollingdoc/issues/new?assignees=iamtekson%2C+Lalitgis%2C+Pratichhya&labels=training&projects=&template=training---knowledge-sharing-checklist.md&title=%5BTraining+%26+collaboration%5D

**Comment by kshitijrajsharma** [comment]
I guess event and training are two different topics ?

**Comment by iamtekson** [comment]
I think we can write `event` and remove the training word. Lets make more generic checklists!

**Comment by iamtekson** [comment]
Since we already implemented the issue template, I am closing this issue and marked as done!
