### ISSUE TITLE
Create a Calendar Invite and Make it sharable

### ISSUE THREAD

**Issue by kshitijrajsharma** [osgeonepal/rollingdoc#6]
Using Google meet we are having issue to share with our group as it exceeds the number of poeple , Plan is to create sharable invite file .ics and Include it in wiki / landing page wherever possible and share it with all members . We can use jitsi meeting constant room '''osgeonepal''' so it won't create confusion every-time , People can simply hop in

**Comment by susmina94** [comment]
I am interested in this issue.

**Comment by kshitijrajsharma** [comment]
Sure Go ahead !
